### ISSUE TITLE
HOW I setting environment variables PIPS_NLP_PAR_SHARED_LIB

### ISSUE THREAD

**Issue by Esnilg** [Argonne-National-Laboratory/PIPS#41]
Hi,

How I Setting environment variables PIPS_NLP_PAR_SHARED_LIB and PIPS_NLP_SHARED_LIB to the location of the parallel and serial shared Libraries correspondingly.? in Ubuntu

some example

thanks you

**Comment by cnpetra** [comment]
This is a Linux question and setting these env variable depends on the shell you’re using. With bash (under Ubuntu) see, for example, https://askubuntu.com/questions/58814/how-do-i-add-environment-variables
