### ISSUE TITLE
The C interface for PIPS needs to be guarded with #ifdef _cplusplus

### ISSUE THREAD

**Issue by abhyshr** [Argonne-National-Laboratory/PIPS#61]
extern "C"" declarations for the functions exported by PIPS do not work with C. These need to be guarded with #ifdef _cplusplus #endif.

**Comment by cnpetra** [comment]
@abhyshr : commit f62fa3550857863ba3e7b11c54b4377e53d89fac pushed the fix you sent me

thanks
