### ISSUE TITLE
Binaries of PIPS-NLP

### ISSUE THREAD

**Issue by tso-martin** [Argonne-National-Laboratory/PIPS#66]
Hello,
Thank you for your work on PIPS. I built PIPS-NLP only and expected to find the binaries `pipsnlp_serial` and `pipsnlp_parallel` (https://github.com/Argonne-National-Laboratory/PIPS/blob/master/PIPS-NLP/README.md). However, I only found the shared objects `lib/libparpipsnlp.so` and `lib/libpipsnlp.so`. Is this correct or did I make a mistake during compilation?

Best regards,
Martin

**Comment by nychiang** [comment]
Do you have MA57? It seems to me these two executables are build [if `HAVE_MA57` is true](https://github.com/Argonne-National-Laboratory/PIPS/blob/f62fa3550857863ba3e7b11c54b4377e53d89fac/PIPS-NLP/CMakeLists.txt#L35C4-L35C13).

**Comment by tso-martin** [comment]
Ok, MA57 was not found automatically, so I had to add it with cmake. The binaries are built now. Thank you!
